---
openapi: 3.0.1
info:
  title: API
  version: '1'
components:
  schemas:
    Game:
      type: object
      properties:
        id:
          type: integer
          example: 982478387
        current_turn:
          type: integer
          example: 0
        players_turn:
          type: integer
          example: 1
        game_state:
          type: string
          example: in_lobby
        winning_score:
          anyOf:
          - type: integer
            example: 250
          - type: 'null'
        winners:
          type: array
          items:
            type: integer
        field:
          type: array
          items:
            type: string
        letter_bag:
          anyOf:
          - type: array
            items:
              type: string
          - type: 'null'
        language:
          anyOf:
          - type: string
          - type: 'null'
        hand_size:
          anyOf:
          - type: integer
          - type: 'null'
        players:
          type: array
          items:
            "$ref": "#/components/schemas/Player"
    Player:
      type: object
      properties:
        id:
          type: integer
          example: 12
        nickname:
          type: string
          example: Biba
        score:
          type: integer
          example: 0
        active_player:
          type: boolean
          example: true
        hand:
          type: array
          items:
            type: string
            example: ''
  securitySchemes:
    JWT:
      name: Authorization
      in: header
paths:
  "/api/v1/new_game":
    post:
      summary: Creates a new game and adds a player to it.
      tags:
      - Gameplay
      parameters: []
      responses:
        '201':
          description: successful
          headers:
            Token:
              type: string
              description: Player's personal token
          content:
            application/json:
              schema:
                properties:
                  game:
                    "$ref": "#/components/schemas/Game"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nickname:
                  type: string
                  example: Biba
              required:
              - nickname
  "/api/v1/join_game/{game_id}":
    parameters:
    - name: game_id
      in: path
      description: Game id
      required: true
      schema:
        type: string
    post:
      summary: Connects player to the game.
      tags:
      - Gameplay
      parameters: []
      responses:
        '200':
          description: successful
          headers:
            Token:
              type: string
              description: Player's personal token
          content:
            application/json:
              schema:
                properties:
                  game:
                    "$ref": "#/components/schemas/Game"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nickname:
                  type: string
                  example: Biba
              required:
              - nickname
  "/api/v1/start_game":
    post:
      summary: Fills all player's hands and starts the game with chosen settings.
      tags:
      - Gameplay
      security:
      - JWT: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                properties:
                  game:
                    "$ref": "#/components/schemas/Game"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                language:
                  type: string
                  example: rus
                  description: Only russian for now.
                hand_size:
                  type: integer
                  example: '8'
                  description: Default for russian is 7.
                winning_score:
                  type: integer
                  example: '120'
                  description: Default is 150.
              required:
              - language
  "/api/v1/submit_turn":
    post:
      summary: Validates turn, updates field, refills player's hand and count player's
        score.
      tags:
      - Gameplay
      security:
      - JWT: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                properties:
                  game:
                    "$ref": "#/components/schemas/Game"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                positions:
                  type: array
                  items:
                    type: integer
                  example:
                  - 112
                  - 113
                  - 114
                letters:
                  type: array
                  items:
                    type: string
                  example:
                  - с
                  - о
                  - н
                hand:
                  type: array
                  items:
                    type: string
                  example:
                  - з
                  - й
                  - ь
                  - щ
              required:
              - positions
              - letters
              - hand
  "/api/v1/exchange":
    post:
      summary: Returns deleted letters from hand to letter bag and drags new ones.
      tags:
      - Gameplay
      security:
      - JWT: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                properties:
                  game:
                    "$ref": "#/components/schemas/Game"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                exchange_letters:
                  type: array
                  items:
                    type: string
                  example:
                  - т
                  - т
                  - ш
                hand:
                  type: array
                  items:
                    type: string
                  example:
                  - з
                  - й
                  - ь
                  - щ
              required:
              - exchange_letters
              - hand
  "/api/v1/skip_turn":
    post:
      summary: Allows player to skip his turn.
      tags:
      - Gameplay
      security:
      - JWT: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                properties:
                  game:
                    "$ref": "#/components/schemas/Game"
  "/api/v1/leave_game":
    post:
      summary: "Sets player's 'active_player' flag to false.\n    An inactive player
        is considered to have left the game and skips his turns. \n    When there
        are no active players, the game is deleted."
      tags:
      - Gameplay
      security:
      - JWT: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: string
                    example: Player left the game!
  "/api/v1/suggest_finishing":
    post:
      summary: "Sets player's 'want_to_end' flag to true. \n    As soon as all players
        'want to end', game ends prematurely."
      tags:
      - Gameplay
      security:
      - JWT: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                properties:
                  game:
                    "$ref": "#/components/schemas/Game"
  "/api/v1/spelling_check":
    post:
      summary: Check if the specified word is in the dictionary.
      tags:
      - Optional
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                properties:
                  correct_spelling:
                    type: boolean
                    example: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                word:
                  type: string
                  example: слово
              required:
              - word
  "/api/v1/games":
    get:
      summary: List of all games in the system.
      tags:
      - Usefull
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                properties:
                  games:
                    type: array
                    items:
                      "$ref": "#/components/schemas/Game"
  "/api/v1/show":
    get:
      summary: Show game by token
      tags:
      - Usefull
      security:
      - JWT: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                properties:
                  game:
                    "$ref": "#/components/schemas/Game"
servers:
- url: http://localhost:8081
